"""merge_role_tables

Revision ID: c5edd477bea9
Revises: 55f55c3df521
Create Date: 2025-03-27 15:02:13.726755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5edd477bea9'
down_revision: Union[str, None] = '55f55c3df521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company_role_rel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company_role_rel',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_time', mysql.TIME(), nullable=False),
    sa.Column('break_time', mysql.TIME(), nullable=False),
    sa.Column('clock_in_status', mysql.ENUM('ACTIVE', 'IDLE', 'PAUSE'), nullable=False),
    sa.Column('schedule_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('supervisor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='user_company_role_rel_ibfk_2'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='user_company_role_rel_ibfk_4'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='user_company_role_rel_ibfk_5'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], name='user_company_role_rel_ibfk_6'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_company_role_rel_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'company_id', 'role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
