"""delete_userrole_table

Revision ID: db24ea92bc7a
Revises: c5edd477bea9
Create Date: 2025-03-27 15:15:12.523326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db24ea92bc7a'
down_revision: Union[str, None] = 'c5edd477bea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), nullable=False),
    sa.Column('valid_from', mysql.DATETIME(), nullable=False),
    sa.Column('valid_until', mysql.DATETIME(), nullable=True),
    sa.Column('assigned_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], name='user_role_ibfk_4'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='user_role_ibfk_3'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_role_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_role_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
